---
# tasks file for ./roles/install_server

# ------------------------------------------------------------------------------
- name: "SERVER | tmux | step 1 | install dependencies"
  become: true
  ansible.builtin.apt:
    pkg: "{{ install_server_tmux.apt_dependencies }}"
    state: present
    force_apt_get: true # apt-get instead of aptitude
  tags:
    - install_server
    - tmux

# ------------------------------------------------------------------------------
- name: "SERVER | tmux | step 2 | install tmux | git clone"
  become: true
  ansible.builtin.git:
    repo: "{{ install_server_tmux.git }}"
    dest: "/opt/tmux"
    force: true
    update: "{{ install_server_tmux.update | bool }}"
    version: master
  tags:
    - install_server
    - tmux

# ------------------------------------------------------------------------------
- name: "SERVER | tmux | step 2.1 | install tmux | run autogen.sh"
  become: true
  ansible.builtin.shell: ./autogen.sh
  args:
    chdir: "/opt/tmux"
    creates: "/opt/tmux/configure"
    executable: /bin/bash
  tags:
    - install_server
    - tmux

- name: "SERVER | tmux | step 2.2 | install tmux | run configure"
  become: true
  ansible.builtin.shell: ./configure
  args:
    chdir: "/opt/tmux"
    creates: "/opt/tmux/Makefile"
    executable: /bin/bash
  tags:
    - install_server
    - tmux

- name: "SERVER | tmux | step 2.3 | install tmux | make and install"
  become: true
  ansible.builtin.shell: set -o pipefail && make && make install
  args:
    chdir: "/opt/tmux"
    executable: /bin/bash
  register: tmux_make_run
  changed_when: tmux_make_run.rc != 0
  tags:
    - install_server
    - tmux

# ------------------------------------------------------------------------------
- name: "SERVER | tmux | step 3.1 | setup tmux plugins | git clone"
  become: true
  become_user: "{{ outer_item.name }}"
  ansible.builtin.git:
    repo: "{{ item.plugins.git }}"
    dest: "{{ item.plugins.path }}"
    force: true
    update: "{{ install_server_tmux.update | bool }}"
    version: "{{ item.plugins.version }}"
  loop: "{{ install_server_tmux.plugins | flatten(levels=1) }}"
  tags:
    - install_server
    - tmux

# ------------------------------------------------------------------------------
- name: "SERVER | tmux | step 5.1 | setup tmux | add base conf file"
  become: true
  become_user: "{{ outer_item.name }}"
  ansible.builtin.template:
    src: tmux/.tmux.conf.j2
    dest: "{{ install_server_tmux_file }}"
    mode: "0660"
  tags:
    - install_server
    - tmux

- name: "SERVER | tmux | step 5.2 | setup tmux | add additional conf file"
  become: true
  become_user: "{{ outer_item.name }}"
  ansible.builtin.template:
    src: "tmux/{{ item }}.j2"
    dest: "{{ install_server_tmux_path }}/{{ item }}"
    mode: "0660"
  loop: "{{ install_server_tmux.add_conf_files | flatten(levels=1) }}"
  tags:
    - install_server
    - tmux

- name: "SERVER | tmux | step 5.3 | setup tmux | add additional script helper"
  become: true
  become_user: "{{ outer_item.name }}"
  ansible.builtin.template:
    src: "tmux/scripts/{{ item }}.j2"
    dest: ".local/bin/{{ item }}"
    mode: "0760"
  loop: "{{ install_server_tmux.add_script_files | flatten(levels=1) }}"
  tags:
    - install_server
    - tmux
