---
# tasks file for ./roles/install_server

# ------------------------------------------------------------------------------
- name: "SERVER | python | install python by apt packages [main]"
  become: true
  ansible.builtin.apt:
    pkg: "{{ install_server_python.apt }}"
    state: present
    force_apt_get: true # apt-get instead of aptitude
  when:
    - install_server_python is defined
    - install_server_python.apt is defined
  tags:
    - install_server
    - install_python

# ------------------------------------------------------------------------------
- name: "SERVER | python | install python by apt packages [dev]"
  become: true
  ansible.builtin.apt:
    pkg: "{{ install_server_python.dev }}"
    state: present
    force_apt_get: true # apt-get instead of aptitude
  when:
    - install_server_config.dev is defined
    - install_server_config.dev | bool
    - install_server_python is defined
    - install_server_python.dev is defined
  tags:
    - install_server
    - install_python
