---
# tasks file for ./roles/install_server

# ------------------------------------------------------------------------------
- name: npm | install npm packages globally [npm install -g]
  become: yes
  become_user: "{{ outer_item.name }}"
  npm:
    name: "{{ item }}"
    # global: yes
  loop: "{{ install_server_npm_pkg | flatten(levels=1) }}"
  when: install_server_npm_pkg is defined
  tags:
    - install_server
    - npm
