---
# tasks file for ./roles/install_server

# ------------------------------------------------------------------------------
- name: "SERVER | ruby | install dependencies [apt]"
  become: true
  ansible.builtin.apt:
    pkg: "{{ install_server_ruby.apt_dependencies }}"
    state: present
    force_apt_get: true # apt-get instead of aptitude
  tags:
    - install_server
    - ruby

# ------------------------------------------------------------------------------
# TODO:
- name: "SERVER | ruby | create a directory, for /etc/zsh/profile.d"
  become: true
  ansible.builtin.file:
    path: "/etc/zsh/profile.d"
    owner: "root"
    group: "root"
    state: directory
    mode: "0755"
  tags:
    - install_server
    - ruby

- name: "SERVER | ruby | set GEM_HOME for all users"
  become: true
  ansible.builtin.copy:
    src: ruby-path.sh
    dest: /etc/zsh/profile.d
    mode: 0644
    # dest: /etc/profile.d
  when:
    - install_server_ruby is defined
    - install_server_ruby.set_path is defined
    - install_server_ruby.set_path | bool
  tags:
    - install_server
    - ruby
