---
# tasks file for ./roles/install_server

# ------------------------------------------------------------------------------
- name: "SERVER | npm | download npm step 1 [get/deb]"
  ansible.builtin.get_url:
    url: "{{ install_server_npm.deb.url }}"
    dest: "/tmp/{{ install_server_npm.deb.file }}"
    mode: "0700"
  tags:
    - install_server
    - npm

- name: "SERVER | npm | install npm step 2 [bash]"
  become: true
  ansible.builtin.command: "/tmp/{{ install_server_npm.deb.file }}"
  register: npm_run_script_install
  changed_when: npm_run_script_install.rc != 0
  tags:
    - install_server
    - npm

- name: "SERVER | npm | install npm step 3 [apt]"
  become: true
  ansible.builtin.apt:
    pkg: "{{ install_server_npm.apt }}"
    state: present
    force_apt_get: true # apt-get instead of aptitude
  tags:
    - install_server
    - npm

# ------------------------------------------------------------------------------
- name: "SERVER | npm | create a directory, for /etc/zsh/profile.d"
  become: true
  ansible.builtin.file:
    path: "/etc/zsh/profile.d"
    # path: /etc/profile.d
    owner: "root"
    group: "root"
    state: directory
    mode: "0755"
  when:
    - install_server_npm is defined
    - install_server_npm.set_path is defined
    - install_server_npm.set_path | bool
  tags:
    - install_server
    - npm

- name: "SERVER | npm | set npm-PATH for all users"
  become: true
  ansible.builtin.copy:
    src: npm-path.sh
    dest: /etc/zsh/profile.d
    # dest: /etc/profile.d
    mode: 0644
  when:
    - install_server_npm is defined
    - install_server_npm.set_path is defined
    - install_server_npm.set_path | bool
  tags:
    - install_server
    - npm
