---
# tasks file for ./roles/install_server

# ------------------------------------------------------------------------------
# CHECK IF SERVICE INSTALLED
- name: "SERVER | snap | check if service installed"
  become: true
  ansible.builtin.command: which snap
  register: is_snap_exist
  changed_when: is_snap_exist.rc not in [0, 1]
  failed_when: is_snap_exist.rc not in [0, 1]
  tags:
    - install_server
    - snap

# ------------------------------------------------------------------------------
- name: "SERVER | snap | install snap services"
  become: true
  community.general.snap:
    name: "{{ item.name }}"
    classic: "{{ item.classic | bool }}"
    # beta: "{{ item.beta | bool }}"
  loop: "{{ install_server_snap | flatten(levels=1) }}"
  when:
    - install_server_snap is defined
    - item.install is defined
    - item.install | bool
    - is_snap_exist.rc is defined
    - is_snap_exist.rc == 0
  tags:
    - install_server
    - snap
