---
# tasks file for ./roles/install_server
#
# will not installed as root, per defined in "install_npm" that this is not need
# here will install per user without root needed

# ------------------------------------------------------------------------------
- name: "SERVER | npm | create a directory, for ~/.npm-packages"
  become: true
  become_user: "{{ outer_item.name }}"
  ansible.builtin.file:
    path: "~/.npm-packages"
    state: directory
    mode: "0750"
  when:
    - install_server_npm_pkg is defined
  tags:
    - install_server
    - npm

# ------------------------------------------------------------------------------
- name: "SERVER | npm | setup NPM prefix"
  become: true
  become_user: "{{ outer_item.name }}"
  ansible.builtin.command: "npm config set prefix ~/.npm-packages"
  when: install_server_npm_pkg is defined
  tags:
    - molecule-idempotence-notest
    - install_server
    - npm

# ------------------------------------------------------------------------------
- name: "SERVER | npm | install npm packages globally"
  become: true
  become_user: "{{ outer_item.name }}"
  community.general.npm:
    name: "{{ item }}"
    path: "~/.npm-packages"
    global: true
  loop: "{{ install_server_npm_pkg | flatten(levels=1) }}"
  when:
    - install_server_npm_pkg is defined
  tags:
    - install_server
    - npm
