---
# tasks file for ./roles/install_server

# ------------------------------------------------------------------------------
- name: "SERVER | deb | install a .deb package from the internet"
  become: true
  ansible.builtin.apt:
    deb: "{{ item.url }}"
  loop: "{{ install_server_dpkg | flatten(levels=1) }}"
  when:
    - install_server_dpkg is defined
    - item.install is defined
    - item.install | bool
  tags:
    - install_server
    - dpkg
