---
# tasks file for ./roles/install_server

# ------------------------------------------------------------------------------
# CHECK IF SERVICE INSTALLED
- name: "SERVER | snap | check if service installed"
  become: true
  ansible.builtin.command: which snap
  register: is_snap_exist
  changed_when: false
  failed_when: false
  when:
    - install_server_snap is defined
  tags:
    - install_server
    - snap

# ------------------------------------------------------------------------------
- name: "SERVER | snap | start udev and snapd"
  become: true
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - udev
    - snapd
  when:
    - install_server_snap is defined
    - is_snap_exist.rc is defined
    - is_snap_exist.rc == 0
  tags:
    - molecule-idempotence-notest
    - install_server
    - snap

# ------------------------------------------------------------------------------
- name: "SERVER | snap | install snap services"
  become: true
  community.general.snap:
    name: "{{ item.name }}"
    classic: "{{ item.classic | default(false) | bool }}"
    channel: "{{ item.channel | default('stable') }}"
  loop: "{{ install_server_snap | flatten(levels=1) }}"
  when:
    - install_server_snap is defined
    - is_snap_exist.rc is defined
    - is_snap_exist.rc == 0
    - item.install is defined
    - item.install | bool
  tags:
    - install_server
    - snap
