---
# tasks file for ./roles/install_server

# ------------------------------------------------------------------------------
- name: "SERVER | nvim | step 1 | install dependencies [apt]"
  become: true
  ansible.builtin.apt:
    pkg: "{{ item }}"
    state: present
    force_apt_get: true # apt-get instead of aptitude
  loop: "{{ install_server_nvim.apt_dependencies | flatten(levels=1) }}"
  tags:
    - install_server
    - nvim

# ------------------------------------------------------------------------------
- name: "SERVER | nvim | step 2.1 | install nvim | git clone"
  become: true
  ansible.builtin.git:
    repo: "{{ install_server_nvim.git }}"
    dest: /opt/nvim
    force: true
    update: "{{ install_server_nvim.update | bool }}"
    version: "{{ install_server_nvim.git_version }}"
  tags:
    - install_server
    - nvim

- name: "SERVER | nvim | step 2.2 | install nvim | git clone | change owner"
  become: true
  ansible.builtin.file:
    path: /opt/nvim
    state: directory
    owner: "{{ outer_item.name }}"
    group: "{{ outer_item.name }}"
    recurse: true
  tags:
    - install_server
    - nvim

# ------------------------------------------------------------------------------
- name: "SERVER | nvim | step 3.1 | install nvim | make clean"
  become: true
  become_user: "{{ outer_item.name }}"
  ansible.builtin.shell: >
    set -o pipefail && make distclean
  args:
    chdir: "/opt/nvim"
    executable: /bin/bash
  register: nvim_make_clean
  changed_when: nvim_make_clean.rc != 0
  tags:
    - install_server
    - nvim

- name: "SERVER | nvim | step 3.2 | install nvim | make and make install"
  become: true
  become_user: "{{ outer_item.name }}"
  ansible.builtin.shell: >
    set -o pipefail &&
    make CMAKE_BUILD_TYPE=RelWithDebInfo CMAKE_INSTALL_PREFIX="$HOME/.local/" &&
    make install
  args:
    chdir: "/opt/nvim"
    executable: /bin/bash
  register: nvim_make_run
  changed_when: nvim_make_run.rc != 0
  tags:
    - install_server
    - nvim

# ------------------------------------------------------------------------------
- name: "SERVER | nvim | step 4 | create conf folders"
  become: true
  become_user: "{{ outer_item.name }}"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ outer_item.name }}"
    group: "{{ outer_item.name }}"
    mode: "0770"
  loop: "{{ install_server_nvim.folders | flatten(levels=1) }}"
  tags:
    - install_server
    - nvim

# ------------------------------------------------------------------------------
- name: "SERVER | nvim | step 5 | setup conf files"
  become: true
  become_user: "{{ outer_item.name }}"
  ansible.builtin.template:
    src: "{{ item.0.path_src }}/{{ item.1 }}.j2"
    dest: "{{ item.0.path_dest }}/{{ item.1 }}"
    owner: "{{ outer_item.name }}"
    group: "{{ outer_item.name }}"
    mode: "0640"
  with_subelements:
    - "{{ install_server_nvim.configs }}"
    - files
  tags:
    - install_server
    - nvim
