---
# tasks file for ./roles/install_server

# ------------------------------------------------------------------------------
- name: "SERVER | go | install"
  become: true
  become_user: "{{ outer_item }}"
  ansible.builtin.command: go install {{ item.source }}
  changed_when: false
  failed_when: false
  loop: "{{ install_server_go_sources | flatten(levels=1) }}"
  when:
    - install_server_go_sources is defined
    - item.install is defined
    - item.install | bool
  tags:
    - install_server
    - go
