---
# tasks file for ./roles/install_server

# ------------------------------------------------------------------------------
- name: install python packages by pip [main/dev]
  become: yes
  become_user: "{{ outer_item.name }}"
  pip:
    name: "{{ item }}"
    executable: pip3
  loop: "{{ install_server_python.pip | flatten(levels=1) }}"
  when: (install_server_config.dev is defined and install_server_config.dev | bool) and (install_server_python is defined and install_server_python.pip is defined)
  tags:
    - install_server
    - install_python
