---
# tasks file for ./roles/install_server

# ------------------------------------------------------------------------------
- name: go-lang | download the go tarball
  become: true
  ansible.builtin.get_url:
    url: "{{ install_server_go.url }}"
    dest: "/usr/local/src/{{ install_server_go.file }}"
    checksum: "{{ install_server_go.checksum }}"
  tags:
    - install_server
    - go

# ------------------------------------------------------------------------------
- name: go-lang | register the current Go version (if any)
  become: true
  ansible.builtin.command: /usr/local/go/bin/go version
  ignore_errors: true
  register: go_version
  changed_when: false
  tags:
    - install_server
    - go

- name: go-lang | remove old installation of Go
  become: true
  ansible.builtin.file:
    path: /usr/local/go
    state: absent
  ignore_errors: true
  when: >
    (go_version is not defined
    and (go_version.stdout is not defined or go_version.stdout == 1)) or (install_server_go is defined
    and install_server_go.version is defined
    and go_version.stdout != install_server_go.version)
  tags:
    - install_server
    - go

# ------------------------------------------------------------------------------
- name: go-lang | extract the Go tarball if Go is not yet installed or not the desired version
  become: true
  unarchive:
    src: "/usr/local/src/{{ install_server_go.file }}"
    dest: /usr/local
    copy: false
  when: >
    (go_version is not defined
    and (go_version.stdout is not defined or go_version.stdout == 1)) or (install_server_go is defined
    and install_server_go.version is defined
    and go_version.stdout is defined
    and go_version.stdout != install_server_go.version) or (install_server_go is defined
    and install_server_go.version is defined
    and go_version.stdout is not defined)
  tags:
    - install_server
    - go

# ------------------------------------------------------------------------------
- name: "create a directory, for /etc/zsh/profile.d"
  become: true
  ansible.builtin.file:
    path: "/etc/zsh/profile.d"
    owner: "root"
    group: "root"
    state: directory
    mode: "0755"
  when: install_server_go is defined and install_server_go.set_path is defined and install_server_go.set_path | bool
  tags:
    - install_server
    - go

- name: go-lang | add the Go bin directory to the PATH environment variable for all users
  become: true
  ansible.builtin.copy:
    src: go-bin.sh
    dest: /etc/zsh/profile.d
    mode: 0644
    # dest: /etc/profile.d
  when: install_server_go is defined and install_server_go.set_path is defined and install_server_go.set_path | bool
  tags:
    - install_server
    - go

- name: go-lang | set GOPATH for all users
  become: true
  ansible.builtin.copy:
    src: go-path.sh
    dest: /etc/zsh/profile.d
    mode: 0644
    # dest: /etc/profile.d
  when: install_server_go is defined and install_server_go.set_path is defined and install_server_go.set_path | bool
  tags:
    - install_server
    - go
