---
# tasks file for ./roles/install_server

# ------------------------------------------------------------------------------
- name: "SERVER | python | install apt python packages"
  become: true
  ansible.builtin.apt:
    pkg: "{{ item.name }}"
    state: present
    force_apt_get: true # apt-get instead of aptitude
  loop: "{{ install_server_python.apt | flatten(levels=1) }}"
  when:
    - install_server_python is defined
    - install_server_python.apt is defined
    - item.install is defined
    - item.install | bool
  tags:
    - install_server
    - install_python

# ------------------------------------------------------------------------------
- name: "SERVER | python | check python version for arg '--break-system-packages'"
  become: true
  ansible.builtin.set_fact:
    install_server_fact_py_extra_args: "--break-system-packages"
  when:
    - install_server_python is defined
    - install_server_python.pip is defined
    - ansible_facts['python_version'] >= "3.11"
  tags:
    - install_server
    - install_python
