---
# tasks file for ./roles/install_server

# ------------------------------------------------------------------------------
# PRE
- name: "SERVER | pre | run pre tasks to collect needed info's"
  ansible.builtin.include_tasks: pre.yml

# ------------------------------------------------------------------------------
# SETUP USERS
- name: "SERVER | user | setup users"
  ansible.builtin.include_tasks: setup_users.yml

# ------------------------------------------------------------------------------
# --- TUNING OS ---
- name: "SERVER | os | run os tuning's"
  ansible.builtin.include_tasks: setup_tun_os.yml
  when:
    - install_server_os_tun is defined
    - install_server_os_tun.install is defined
    - install_server_os_tun.install | bool

# ------------------------------------------------------------------------------
# DEFAULT PACKAGES
- name: "SERVER | apt | install apt packages"
  ansible.builtin.include_tasks: install_apt.yml

# ------------------------------------------------------------------------------
# DPKG PACKAGES
- name: "SERVER | dpkg | install dpkg packages"
  ansible.builtin.include_tasks: install_dpkg.yml

# ------------------------------------------------------------------------------
# SNAP PACKAGES
- name: "SERVER | snap | install snap packages"
  ansible.builtin.include_tasks: install_snap.yml

# ------------------------------------------------------------------------------
# INSTALL GIT
# - will be installed per client, need to set clients
- name: "SERVER | git | install git (per user)"
  ansible.builtin.include_tasks: install_git.yml
  loop: "{{ clients | flatten(levels=1) }}"
  loop_control:
    loop_var: outer_item
  when:
    - install_server_config.inst_git_conf is defined
    - install_server_config.inst_git_conf | bool
    - clients is defined
    - outer_item.dev is defined
    - outer_item.dev | bool

# ------------------------------------------------------------------------------
# INSTALL ZSH
# - will be installed per client, need to set clients
- name: "SERVER | zsh | install zsh (per user)"
  ansible.builtin.include_tasks: install_zsh.yml
  loop: "{{ clients | flatten(levels=1) }}"
  loop_control:
    loop_var: outer_item
  when:
    - install_server_config.inst_zsh_conf is defined
    - install_server_config.inst_zsh_conf | bool
    - clients is defined
    - outer_item.dev is defined
    - outer_item.dev | bool

# ------------------------------------------------------------------------------
# SUFFIX
- name: "SERVER | suffix | run suffix tasks to set specific conf's"
  ansible.builtin.include_tasks: suffix.yml

# ------------------------------------------------------------------------------
# INSTALL TMUX
# - will be installed per client, need to set clients
- name: "SERVER | tmux | install tmux (per user)"
  ansible.builtin.include_tasks: install_tmux.yml
  loop: "{{ clients | flatten(levels=1) }}"
  loop_control:
    loop_var: outer_item
  when:
    - install_server_config.inst_tmux_conf is defined
    - install_server_config.inst_tmux_conf | bool
    - clients is defined
    - outer_item.dev is defined
    - outer_item.dev | bool

# ------------------------------------------------------------------------------
# INSTALL NVIM
# - will be installed per client, need to set clients
- name: "SERVER | nvim | install nvim (per user)"
  ansible.builtin.include_tasks: install_nvim.yml
  loop: "{{ clients | flatten(levels=1) }}"
  loop_control:
    loop_var: outer_item
  when:
    - install_server_config.inst_nvim_conf is defined
    - install_server_config.inst_nvim_conf | bool
    - clients is defined
    - outer_item.dev is defined
    - outer_item.dev | bool

# ------------------------------------------------------------------------------
# PYTHON PACKAGES
- name: "SERVER | python | install python"
  ansible.builtin.include_tasks: install_python.yml
  when:
    - install_server_config.apt_python is defined
    - install_server_config.apt_python | bool

# - will be installed per client, need to set clients
- name: "SERVER | python | install python packages (per user)"
  ansible.builtin.include_tasks: install_python_pkg.yml
  loop: "{{ clients | flatten(levels=1) }}"
  loop_control:
    loop_var: outer_item
  when:
    - install_server_config.apt_python is defined
    - install_server_config.apt_python | bool
    - clients is defined
    - outer_item.dev is defined
    - outer_item.dev | bool

# ------------------------------------------------------------------------------
# GO PACKAGES
# - will be installed per client, need to set clients
- name: "SERVER | go | install go packages (per user)"
  ansible.builtin.include_tasks: install_go_pkg.yml
  loop: "{{ clients | flatten(levels=1) }}"
  loop_control:
    loop_var: outer_item
  when:
    - install_server_config.snap_go is defined
    - install_server_config.snap_go | bool
    - clients is defined
    - outer_item.dev is defined
    - outer_item.dev | bool

# ------------------------------------------------------------------------------
# NPM PACKAGES
# - will be installed per client, need to set clients
- name: "SERVER | npm | install npm packages (per user)"
  ansible.builtin.include_tasks: install_npm_pkg.yml
  loop: "{{ clients | flatten(levels=1) }}"
  loop_control:
    loop_var: outer_item
  when:
    - install_server_config.snap_node is defined
    - install_server_config.snap_node | bool
    - clients is defined
    - outer_item.dev is defined
    - outer_item.dev | bool

# ------------------------------------------------------------------------------
# JAVA PACKAGES
- name: "SERVER | java | setup java configs"
  ansible.builtin.include_tasks: setup_java.yml
  when: >-
    (install_server_config.apt_java_jre_headless is defined and install_server_config.apt_java_jre_headless | bool) or (install_server_config.apt_java_jdk is defined and install_server_config.apt_java_jdk | bool)
