---
# tasks file for ./roles/install_server

# ------------------------------------------------------------------------------
- name: "SERVER | PRE | run apt cache update"
  become: true
  ansible.builtin.apt:
    force_apt_get: true
    update_cache: true
  changed_when: false
  tags:
    - install_server
    - pre

# ------------------------------------------------------------------------------
- name: "SERVER | PRE | check available shells"
  ansible.builtin.command: cat /etc/shells
  register: install_server_reg_shells_output
  changed_when: false
  tags:
    - install_server
    - pre
    - shell

- name: "SERVER | PRE | set preferred shell"
  ansible.builtin.set_fact:
    install_server_preferred_shell:
      shell: "{{ item.shell }}"
      aliases_path: "{{ item.aliases_path }}"
  loop:
    - shell: /bin/sh
      aliases_path: ~/.bashrc
      profile_d: /etc/profile.d
    - shell: /bin/bash
      aliases_path: ~/.bashrc
      profile_d: /etc/profile.d
    - shell: /bin/zsh
      aliases_path: ~/.zshrc
      profile_d: /etc/zsh/profile.d
  loop_control:
    label: "{{ item.shell }}"
  when: item.shell in install_server_reg_shells_output.stdout_lines
  tags:
    - install_server
    - pre
    - shell

# ------------------------------------------------------------------------------
# GO CONFIG (user)
- name: "SERVER | go | set GEM_HOME for all users"
  become: true
  ansible.builtin.copy:
    src: go-path.sh
    dest: "{{ install_server_preferred_shell.profile_d }}"
    mode: 0644
  when:
    - install_server_config.snap_go is defined
    - install_server_config.snap_go | bool
  tags:
    - install_server
    - go

# RUBY CONFIG (user)
- name: "SERVER | ruby | set GEM_HOME for all users"
  become: true
  ansible.builtin.copy:
    src: ruby-path.sh
    dest: "{{ install_server_preferred_shell.profile_d }}"
    mode: 0644
  when:
    - install_server_config.snap_ruby is defined
    - install_server_config.snap_ruby | bool
  tags:
    - install_server
    - ruby

# NPM CONFIG (user)
- name: "SERVER | npm | set npm-PATH for all users"
  become: true
  ansible.builtin.copy:
    src: npm-path.sh
    dest: "{{ install_server_preferred_shell.profile_d }}"
    mode: 0644
  when:
    - install_server_config.snap_node is defined
    - install_server_config.snap_node | bool
  tags:
    - install_server
    - npm
