---
# tasks file for setup_users

# ------------------------------------------------------------------------------
# - name: delete user accounts
#  become: true
#  user:
#  name: "{{ item.name }}"
#  state: absent
#  remove: yes
#  force: yes
#  loop: "{{ clients |flatten(levels=1) }}"

# ------------------------------------------------------------------------------
- name: "SERVER | user | update user accounts"
  become: true
  ansible.builtin.user:
    name: "{{ item.name }}"
    state: present
    shell: "{{ item.shell | default(install_server_preferred_shell.shell) }}"
    groups: "{{ item.group | default('adm, cdrom, sudo') }}"
    createhome: "{{ item.createhome | default('true') | bool }}"
    # sudo apt install whois && mkpasswd --method=sha-512
    password: "{{ item.password }}"
    # update_password: on_create
  loop: "{{ clients | flatten(levels=1) }}"
  when:
    - clients is defined
    - item.updateOrCreate is defined
    - item.updateOrCreate | bool
  tags:
    - install_server
    - user_setup

# --- DEFAULT FOLDER ---
- name: "SERVER | folder | create default folder per client"
  become: true
  become_user: "{{ item.name }}"
  ansible.builtin.file:
    path: "~/.local/bin"
    state: directory
    mode: "0700"
  loop: "{{ clients | flatten(levels=1) }}"
  when:
    - clients is defined
  tags:
    - install_server
    - user_setup
