---
# tasks file for ./roles/install_server

# ------------------------------------------------------------------------------

- name: "SERVER | java | set java env variables into /etc/environment"
  become: true
  ansible.builtin.lineinfile:
    dest: "/etc/environment"
    state: present
    regexp: "^{{ item.variable }}="
    line: "{{ item.variable }}={{ item.path }}"
  loop: "{{ install_server_java.os_env | flatten(levels=1) }}"
  when:
    - install_server_java is defined
    - install_server_java.os_env is defined
    - item.variable is defined
    - item.path is defined
  tags:
    - install_server
    - install_java
