---
# tasks file for ./roles/install_server

# ------------------------------------------------------------------------------
# GO CONFIG (user)
- name: "SERVER | suffix | base | set base paths global"
  become: true
  ansible.builtin.copy:
    src: base-path.sh
    dest: "{{ item }}"
    mode: "0644"
  loop:
    - /etc/profile.d
    - "{{ install_server_preferred_shell.profile_d }}"
  tags:
    - install_server
    - paths

# ------------------------------------------------------------------------------
# GO CONFIG (user)
- name: "SERVER | suffix | go | set go paths global"
  become: true
  ansible.builtin.copy:
    src: go-path.sh
    dest: "{{ item }}"
    mode: "0644"
  loop:
    - /etc/profile.d
    - "{{ install_server_preferred_shell.profile_d }}"
  # when:
  #   - install_server_config.snap_go is defined
  #   - install_server_config.snap_go | bool
  tags:
    - install_server
    - go

# RUBY CONFIG (user)
- name: "SERVER | suffix | ruby | set gem paths global"
  become: true
  ansible.builtin.copy:
    src: ruby-path.sh
    dest: "{{ item }}"
    mode: "0644"
  loop:
    - /etc/profile.d
    - "{{ install_server_preferred_shell.profile_d }}"
  # when:
  #   - install_server_config.snap_ruby is defined
  #   - install_server_config.snap_ruby | bool
  tags:
    - install_server
    - ruby

# NPM CONFIG (user)
- name: "SERVER | suffix | npm | set npm paths global"
  become: true
  ansible.builtin.copy:
    src: npm-path.sh
    dest: "{{ item }}"
    mode: "0644"
  loop:
    - /etc/profile.d
    - "{{ install_server_preferred_shell.profile_d }}"
  # when:
  #   - install_server_config.snap_node is defined
  #   - install_server_config.snap_node | bool
  tags:
    - install_server
    - npm
# # ------------------------------------------------------------------------------
# - name: "SERVER | suffix | run | run paths per user"
#   become: true
#   become_user: "{{ item.name }}"
#   ansible.builtin.shell: |
#     . /etc/profile.d/base-path.sh
#     . /etc/profile.d/go-path.sh
#     . /etc/profile.d/ruby-path.sh
#     . /etc/profile.d/npm-path.sh
#   args:
#     executable: /bin/bash
#   changed_when: false
#   loop: "{{ clients | flatten(levels=1) }}"
#   tags:
#     - install_server
#     - paths
