---
# tasks file for ./roles/install_server

# ------------------------------------------------------------------------------
# hook templates
- name: "init tunning's step:: copy template sysctl.conf"
  become: true
  ansible.builtin.template:
    src: "sysctl.conf.j2"
    dest: "/etc/sysctl.conf"
    mode: "0644"
  register: tunning_network_result
  tags:
    - install_server
    - apt

- name: "init tunning's step:: run 'sysctl -p --system'"
  become: true
  ansible.builtin.command: sysctl -p --system
  when:
    - tunning_network_result is defined
    - and tunning_network_result.changed is defined
    - and tunning_network_result.changed | bool
  tags:
    - install_server
    - apt
