---
- name: Converge
  hosts: all
  tasks:
    - name: "Include ansible-install-server"
      ansible.builtin.include_role:
        name: "ansible-install-server"
  vars:
    # --- in inventory ---
    clients:
      - name: ubuntu
        dev: true
        updateOrCreate: false
    install_server_service_name: default-server
    install_server_git_user: ubuntu
    install_server_git_email: ubuntu
    # some version manually needs to checked and updated
    install_server_links_to_check_update:
      mongodb_pgp: https://pgp.mongodb.com/server-7.0.asc
      mongodb_distribution: jammy/mongodb-org/7.0
      # https://snapcraft.io/node
      snap_node_version: 20
      java_version: 21
    # --- in playbook ---
    install_server_config:
      env_tun_setup: true
      # APT (1) -------------------------------
      apt_base: true
      apt_auth_priv: true
      apt_cert: true
      apt_archive: true
      apt_dev: true
      apt_build: true
      apt_libs: true
      # APT (2) -------------------------------
      apt_snap: true
      apt_vpn_resolvconf: true
      apt_vpn_wireguard: true
      apt_vpn_openvpn: true
      apt_vpn_openconnect: true
      apt_php: true
      # apt_rasp_pi_pkg: false
      apt_qemu_guest_agent: true
      # DPKG ----------------------------------
      # dpkg_...: true
      # SNAP ----------------------------------
      # snap_juju: false
      # snap_maas: false
      # snap_microk8s: false
      snap_kubectl: true
      snap_helm: true
      # snap_multipass: false
      snap_btop: true
      snap_glow: true
      snap_go: true
      snap_node: true
      snap_ruby: true
      # snap_openjdk: false
      # snap_openjfx: false
      # OTHER --------------------------------
      apt_git_conf: true
      apt_zsh_conf: true
      git_tmux_conf: true
      # PYTHON --------------------------------
      python_pip_update: true # if pip should update all installed pkg's
      apt_python: true
      apt_python_pip: true
      apt_python_venv: true
      apt_python_dev: true
      pip_s_tui: true
      pip_virtualenv: true
      pip_autopep8: true
      pip_black: true
      pip_mypy: true
      pip_pre_commit: true
      pip_openconnect_sso: true
      pip_ansible: true
      # NPM --------------------------------
      # npm_typescript: false
      # GO --------------------------------
      go_kompose: true
      go_act: true
      # OTHER --------------------------------
      mongodb: true
      apt_java_jre_headless: true
      apt_java_jdk: true
      apt_java_ant: true
