---
- name: Converge
  hosts: all
  tasks:
    - name: "Include ansible-install-server"
      ansible.builtin.include_role:
        name: "ansible-install-server"
  vars:
    # --- in inventory ---
    clients:
      - name: ubuntu
        dev: true
        updateOrCreate: false
    install_server_service_name: default-server
    install_server_git_user: ubuntu
    install_server_git_email: ubuntu
    # some version manually needs to checked and updated
    install_server_links_to_check_update:
      # https://snapcraft.io/node
      snap_node_version: 21
      java_version: 21
    # --- in playbook ---
    install_server_config:
      # APT (1) -------------------------------
      apt_base: true
      apt_auth_priv: true
      apt_cert: true
      apt_archive: true
      apt_dev: true
      apt_build: true
      apt_libs: true
      # APT (2) -------------------------------
      apt_php: true
      apt_lua: true
      apt_java_jre_headless: true
      apt_java_jdk: true
      apt_java_ant: true
      apt_java_maven: true
      apt_java_gradle: true
      # APT (3) -------------------------------
      apt_snap: true
      apt_qemu_guest_agent: true
      # apt_rasp_pi_pkg: false
      apt_vpn_resolvconf: true
      apt_vpn_wireguard: true
      apt_vpn_openvpn: true
      apt_vpn_openconnect: true
      # apt_latex: false
      # apt_pandoc: false
      apt_john_the_ripper: true
      apt_nmap: true
      # DPKG ----------------------------------
      # dpkg_...: true
      # SNAP ----------------------------------
      # snap_juju: false
      # snap_maas: false
      # snap_microk8s: false
      snap_kubectl: true
      snap_helm: true
      # snap_multipass: false
      snap_btop: true
      snap_glow: true
      snap_go: true
      # snap_node: false
      # snap_openjdk: false
      # snap_openjfx: false
      snap_ruby: false
      # need to run "rustup default stable"
      snap_rust: false
      snap_shellcheck: true
      snap_john_the_ripper: false
      snap_nmap: false
      # # FLATHUB ----------------------------------
      # flatpak_john_the_ripper: false
      # flatpak_nmap: false
      # OTHER --------------------------------
      inst_git_conf: true
      inst_fonts: true
      inst_zsh_conf: true
      inst_tmux_conf: true
      inst_nvim_conf: true
      # PYTHON --------------------------------
      apt_python: true
      apt_python_pip: true
      apt_python_venv: true
      apt_python_dev: true
      pip_s_tui: true
      pip_virtualenv: true
      pip_autopep8: true
      pip_black: true
      pip_mypy: true
      pip_pre_commit: true
      pip_openconnect_sso: true
      pip_ansible: true
      # NPM --------------------------------
      # npm_typescript: false
      # GO --------------------------------
      # go_kompose: true
      # go_act: true
