---
- name: Converge
  hosts: all
  tasks:
    - name: "Include ansible-install-server"
      include_role:
        name: "ansible-install-server"
  vars:
    # --- in inventory ---
    clients:
      - name: ubuntu
        dev: yes
        updateOrCreate: no
    install_server_service_name: default-server
    install_server_git_user: ubuntu
    install_server_git_email: ubuntu
    # --- in playbook ---
    install_server_config:
      dev: true
      env_tun_setup: true
      # APT (1) -------------------------------
      apt_base: true
      apt_archive: true
      apt_dev: true
      apt_build: true
      apt_libs: true
      # APT (2) -------------------------------
      apt_snap: true
      apt_vpn: true
      apt_go: true
      apt_php: true
      # apt_rasp_pi_pkg: false
      # apt_qemu_guest_agent: false
      # DPKG ----------------------------------
      # dpkg_...: false
      # SNAP ----------------------------------
      snap_microk8s: true
      # snap_multipass: false
      snap_btop: true
      # OTHER --------------------------------
      git: true
      zsh: true
      tmux: true
      # PYTHON --------------------------------
      # python: false
      # python_pip: false
      # python_venv: false
      # python_dev: false
      # pip_s_tui: false
      # pip_virtualenv: false
      # pip_autopep8: false
      # pip_black: false
      # pip_pre_commit: false
      # pip_openconnect_sso: false
      # OTHER --------------------------------
      go_kompose: true
      ruby: true
      # npm: false
      # mongodb: false
      java: true
      java_ant: true
