---
- name: Converge
  hosts: all
  tasks:
    - name: "Include ansible-install-server"
      include_role:
        name: "ansible-install-server"
  vars:
    # --- in inventory ---
    clients:
      - name: ubuntu
        dev: yes
        updateOrCreate: no
    install_server_service_name: default-server
    install_server_git_user: ubuntu
    install_server_git_email: ubuntu
    # --- in playbook ---
    install_server_config:
      env_tun_setup: true
      # APT (1) -------------------------------
      apt_base: true
      apt_archive: true
      apt_dev: true
      apt_build: true
      apt_libs: true
      # APT (2) -------------------------------
      apt_snap: true
      apt_vpn: true
      apt_php: true
      # apt_rasp_pi_pkg: false
      apt_qemu_guest_agent: true
      # DPKG ----------------------------------
      # dpkg_...: false
      # SNAP ----------------------------------
      # snap_juju: false
      # snap_maas: false
      # snap_microk8s: false
      snap_kubectl: true
      snap_helm: true
      # snap_multipass: false
      snap_btop: true
      snap_glow: true
      snap_go: true
      # snap_node: false
      snap_ruby: true
      # OTHER --------------------------------
      git: true
      zsh: true
      tmux: true
      # PYTHON --------------------------------
      python: true
      python_pip: true
      python_pip_update: true
      python_venv: true
      python_dev: true
      pip_s_tui: true
      pip_virtualenv: true
      pip_autopep8: true
      pip_black: true
      pip_mypy: true
      pip_pre_commit: true
      pip_openconnect_sso: true
      pip_ansible: true
      # NPM --------------------------------
      # npm_typescript: false
      # GO --------------------------------
      go_kompose: true
      go_act: true
      # OTHER --------------------------------
      # mongodb: false
      java: true
      java_ant: true
