---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint . -c .yamllint
  ansible-lint -c .ansible-lint
platforms:
  - name: ubuntu-23.04
    ansible_user: ubuntu
    image: mvladislav/docker-ubuntu-systemd-sudo-ansible:23.04
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /tmp
    privileged: true
    cgroupns_mode: host
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /usr/bin/python3
verifier:
  name: ansible
  options:
    v: 2
    notest: molecule-idempotence-notest
